logging:
    file:
        name: logs/sboard.log
    level:
        root: info
mybatis:
    mapper-locations: classpath:mappers/**/*.xml
server:
    port: 8080
    servlet:
        context-path: /sboard
spring:
    application:
        name: sboard
        version: ${version}
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@//3.34.176.250:1522/XE
        username: sboard
        password: vpcndrl2634
    devtools:
        livereload:
          enabled: true
    jpa:
        hibernate:
            ddl-auto: update
            naming:
               physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    security:
        user:
            name: user
            password: 1234
            roles : ADMIN
jwt:
    issuer: hanto0916@gmail.com
    secret: C6ADBBEF28B5495A783CB618A2D1D10C